# This rule is not used by the project kafka-connect-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kafka-connect.b1zzu.net.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafka-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-admin-role
rules:
- apiGroups:
  - kafka-connect.b1zzu.net
  resources:
  - clusters
  verbs:
  - '*'
- apiGroups:
  - kafka-connect.b1zzu.net
  resources:
  - clusters/status
  verbs:
  - get
