apiVersion: kafka-connect.b1zzu.net/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
  labels:
    app.kubernetes.io/name: kafka-connect-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  config:
    bootstrap.servers: my-cluster-kafka-bootstrap:9092
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    group.id: connect-my-cluster
    config.storage.topic: connect-my-cluster-configs
    offset.storage.topic: connect-my-cluster-offsets
    status.storage.topic: connect-my-cluster-status
    config.storage.replication.factor: "1"
    offset.storage.replication.factor: "1"
    status.storage.replication.factor: "1"
