apiVersion: kafka-connect.b1zzu.net/v1alpha1
kind: Connector
metadata:
  labels:
    app.kubernetes.io/name: kafka-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-connector
spec:
  cluster:
    name: my-cluster
  config:
    connector.class: org.apache.kafka.connect.mirror.MirrorHeartbeatConnector
    source.cluster.alias: source
    target.cluster.alias: target
