apiVersion: kafka-connect.b1zzu.net/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: kafka-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-cluster
spec:
  replicas: 2
  properties:
    bootstrap.servers: my-cluster-kafka-bootstrap:9092
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    group.id: my-cluster-connect
    config.storage.topic: my-cluster-connect-configs
    offset.storage.topic: my-cluster-connect-offsets
    status.storage.topic: my-cluster-connect-status
